//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K9.Globalisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K9.Globalisation.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Save The Wolf.
        /// </summary>
        public static string AboutNineStarKi {
            get {
                return ResourceManager.GetString("AboutNineStarKi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further Reading.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Donated.
        /// </summary>
        public static string AmountDonatedLabel {
            get {
                return ResourceManager.GetString("AmountDonatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You would like to donate:.
        /// </summary>
        public static string AmountToDonateLabel {
            get {
                return ResourceManager.GetString("AmountToDonateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site is under development and new features are being added continuously. Your feedback is welcome. Please visit the support page to get in touch..
        /// </summary>
        public static string BetaWarning {
            get {
                return ResourceManager.GetString("BetaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        public static string Centre {
            get {
                return ResourceManager.GetString("Centre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Amount.
        /// </summary>
        public static string ChangeAmount {
            get {
                return ResourceManager.GetString("ChangeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        public static string Colour {
            get {
                return ResourceManager.GetString("Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon....
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website has been created to raise money to save our beloved Wolf aka Pisit Domprasong or Dan, who is struggling with ailing health..
        /// </summary>
        public static string CompanyBlurbFooter {
            get {
                return ResourceManager.GetString("CompanyBlurbFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website has been created to raise money to save our beloved Wolf aka Pisit Domprasong or Dan, who is struggling with ailing health..
        /// </summary>
        public static string CompanyDescription {
            get {
                return ResourceManager.GetString("CompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CompanyLegalDescription {
            get {
                return ResourceManager.GetString("CompanyLegalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website has been created to raise money to save our beloved Wolf aka Pisit Domprasong or Dan, who is struggling with ailing health..
        /// </summary>
        public static string CompanyShortDescription {
            get {
                return ResourceManager.GetString("CompanyShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string coreearth_description {
            get {
                return ResourceManager.GetString("coreearth_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string coreearth_health {
            get {
                return ResourceManager.GetString("coreearth_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string coreearth_trigram {
            get {
                return ResourceManager.GetString("coreearth_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CurrencyLabel {
            get {
                return ResourceManager.GetString("CurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Email Address.
        /// </summary>
        public static string CustomerEmailLabel {
            get {
                return ResourceManager.GetString("CustomerEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CustomerLabel {
            get {
                return ResourceManager.GetString("CustomerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirthLabel {
            get {
                return ResourceManager.GetString("DateOfBirthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donated On.
        /// </summary>
        public static string DonatedOnLabel {
            get {
                return ResourceManager.GetString("DonatedOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation.
        /// </summary>
        public static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much would you like to donate?.
        /// </summary>
        public static string DonationAmountLabel {
            get {
                return ResourceManager.GetString("DonationAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making a donation to Save The Wolf will help to buy life-saving herbal and orthomolecular medicines, as well as integrative and holistic therapies. It will also help towards the cost of living. As Dan is not a permanent resident or citizen of the UK, &lt;strong&gt;he is not entitled to any benefits or disability allowance&lt;/strong&gt;. He has been struggling to work to be able to provide for himself, but his ailing health is making this increasingly difficult, not to say impossible..
        /// </summary>
        public static string DonationBlurb {
            get {
                return ResourceManager.GetString("DonationBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;{Title}&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    html
        ///    {
        ///        margin: 0;
        ///        padding: 0;
        ///        font-family: &quot;Segoe UI&quot; , Verdana, Helvetica, Sans-Serif;
        ///        font-size: 100%;
        ///        text-rendering: optimizeLegibility !important;
        ///        -webkit-font-smoothing: antialiased !important;
        ///        margin: 0; 
        ///        color: #333;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;body&gt;
        ///&lt;p class=&quot;text&quot;&gt;Dear Team,&lt;/p&gt;
        ///&lt;p class=&quot;text&quot;&gt;We have received a do [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DonationReceivedEmail {
            get {
                return ResourceManager.GetString("DonationReceivedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donations.
        /// </summary>
        public static string Donations {
            get {
                return ResourceManager.GetString("Donations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your donation was received. Thank you!.
        /// </summary>
        public static string DonationSuccessful {
            get {
                return ResourceManager.GetString("DonationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation Received.
        /// </summary>
        public static string DonationSuccessfulTitle {
            get {
                return ResourceManager.GetString("DonationSuccessfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation To.
        /// </summary>
        public static string DonationTo {
            get {
                return ResourceManager.GetString("DonationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation To Save The Wolf.
        /// </summary>
        public static string DonationToNineStar {
            get {
                return ResourceManager.GetString("DonationToNineStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string fire_description {
            get {
                return ResourceManager.GetString("fire_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string fire_health {
            get {
                return ResourceManager.GetString("fire_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string fire_trigram {
            get {
                return ResourceManager.GetString("fire_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string HealthLabel {
            get {
                return ResourceManager.GetString("HealthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string heaven_description {
            get {
                return ResourceManager.GetString("heaven_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string heaven_health {
            get {
                return ResourceManager.GetString("heaven_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string heaven_trigram {
            get {
                return ResourceManager.GetString("heaven_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star ki astrology horoscope love relationships.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string lake_description {
            get {
                return ResourceManager.GetString("lake_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string lake_health {
            get {
                return ResourceManager.GetString("lake_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string lake_trigram {
            get {
                return ResourceManager.GetString("lake_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a Donation.
        /// </summary>
        public static string MakeDonation {
            get {
                return ResourceManager.GetString("MakeDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string mountain_description {
            get {
                return ResourceManager.GetString("mountain_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string mountain_health {
            get {
                return ResourceManager.GetString("mountain_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string mountain_trigram {
            get {
                return ResourceManager.GetString("mountain_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine star Ki.
        /// </summary>
        public static string nine_star_ki_title {
            get {
                return ResourceManager.GetString("nine_star_ki_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;{Title}&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    html
        ///    {
        ///        margin: 0;
        ///		padding: 0;
        ///		font-family: &quot;Segoe UI&quot; , Verdana, Helvetica, Sans-Serif;
        ///		font-size: 100%;
        ///		text-rendering: optimizeLegibility !important;
        ///		-webkit-font-smoothing: antialiased !important;
        ///        margin: 0; 
        ///        color: #333;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Dear {FirstName},&lt;/p&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Your password has been reset. Please [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PasswordResetEmail {
            get {
                return ResourceManager.GetString("PasswordResetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save The Wolf.
        /// </summary>
        public static string SaveTheWolf {
            get {
                return ResourceManager.GetString("SaveTheWolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Soil energies are maternal and caring in nature and are happiest when they are serving and supporting others.
        ///    They are not natural born leaders, but work diligently and tirelessly to get the job done. 
        ///    Number two soil energies are probably the most reliable of all the energies.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Soil energies are generally patient, resilient and calm, although they may be prone to worry and anxiety, especially with regards to others. 
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Soil energies are generally very sociabl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string soil_description {
            get {
                return ResourceManager.GetString("soil_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Being sensitive by nature, soil energies do not typically have a strong constitution. In Traditional Chinese Medicine, the earth element governs the spleen, pancreas and stomach and
        ///    there for the lymphatic and immune systems. Soil energies must take extra care to look after these organs with a healthy balanced diet which does not contain excessive carbohydrate.
        ///    It is also advisable to engage in activities which are calming, such as meditation and yoga, in order to avoid excessive anxiety  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string soil_health {
            get {
                return ResourceManager.GetString("soil_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Owing to their supportive, caring nature, many soil energies make excellent nurses, carers, social workers as well as teachers and various types of assistants.
        ///    Their strong connection with the land also makes soil energies excellent at careers in agriculture or horticulture.
        ///    On the other hand, any job involving group work would also be well suited to number two soil energies.
        ///&lt;/p&gt;.
        /// </summary>
        public static string soil_occupations {
            get {
                return ResourceManager.GetString("soil_occupations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Number two soils are so focussed on supporting and helping others than they may not take enough time out for themselves. 
        ///    As such, they may be prone to getting a bit worn out. They should be encouraged to get a healthy balance between work and play and sometimes put themselves first.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    It is also very important for soil energies not to stagnate. Frequent walks and exercise are very good for this reason.
        ///&lt;/p&gt;.
        /// </summary>
        public static string soil_personal_development {
            get {
                return ResourceManager.GetString("soil_personal_development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Three yin lines, representing the consistent nature of earth as well as the receptive qualities of the mother, who wishes to nurture and serve. 
        ///    She requires support from the family to do this. There are no yang lines and as such, yang must be provided by the other signs.
        ///&lt;/p&gt;.
        /// </summary>
        public static string soil_trigram {
            get {
                return ResourceManager.GetString("soil_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;{Title}&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    html
        ///    {
        ///        margin: 0;
        ///        padding: 0;
        ///        font-family: &quot;Segoe UI&quot; , Verdana, Helvetica, Sans-Serif;
        ///        font-size: 100%;
        ///        text-rendering: optimizeLegibility !important;
        ///        -webkit-font-smoothing: antialiased !important;
        ///        margin: 0; 
        ///        color: #333;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;body&gt;
        ///&lt;p class=&quot;text&quot;&gt;Dear {FirstName},&lt;/p&gt;
        ///&lt;p class=&quot;text&quot;&gt;Thank you for  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SupportQuery {
            get {
                return ResourceManager.GetString("SupportQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Thunder energies embody the power of spring and have plenty of vitality and energy. They are more about doing than being and like to take action and initiate.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Thunder energies are generally very positive and joyful, and their optimism and abundant energy as well as their ability to take strong action makes them great pioneers in any field they turn their attention to. 
        ///    However, in their constant pursuit of new pastures, they may not stick around long enough to figure out the de [rest of string was truncated]&quot;;.
        /// </summary>
        public static string thunder_description {
            get {
                return ResourceManager.GetString("thunder_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    The wood element governs the liver and gallbladder. 
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    It is advisable for thunder energies to avoid eating two to three hours before sleep as well as overeating.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    It is also wise to avoid too many late nights, as this is the time when the liver repairs itself the most.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Eating an abundance of green leafy vegetables is especially important for thunder energies, 
        ///    as well as citrus fruits such as lemons, limes and grapefruits and apple cider vinegar, w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string thunder_health {
            get {
                return ResourceManager.GetString("thunder_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Thunder energies have tremendous potential for planning and seeing the road ahead, without getting bogged down in details. They are often able to find elegant solutions to the
        ///    most complex problems, providing a clear vision of what needs to be done. For this reason, they may excel in computing, science, research as well as in business intelligence and consulting, to name a few.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Thunder energies can also make energetic performers, artists and speakers and breaking ground in thes [rest of string was truncated]&quot;;.
        /// </summary>
        public static string thunder_occupations {
            get {
                return ResourceManager.GetString("thunder_occupations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Thunder energies benefit greatly from taking time to reflect and take stock. They should also endeavour to see projects through to completion.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Socially, thunder energies derive a lot of benefit from focussing more on listening to others. In addition, it is good to remember that the positive and energetic nature of
        ///    thunder may be overbearing and intimitading to some.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    It is important for thunder energies to build up their energy reserves with sufficient sleep, res [rest of string was truncated]&quot;;.
        /// </summary>
        public static string thunder_personal_development {
            get {
                return ResourceManager.GetString("thunder_personal_development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    A strong yang, base line opening up into two yin lines. This represents growth and action and the awakening of dawn and spring as well as action and spontaneity.
        ///&lt;/p&gt;.
        /// </summary>
        public static string thunder_trigram {
            get {
                return ResourceManager.GetString("thunder_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Like water, this energy can resemble a lively mountain stream or, conversely, a deep lake or ocean. Water energies can be adventurous and vivacious, or quiet, reflective and withdrawn.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Water energies benefit greatly from having a container to structure them, just as the river needs the river banks. Without this, they may tend towards chaos and lack of discipline.
        ///&lt;/p&gt;
        ///&lt;p&gt;Water energies can be very sensitive, intuitive and philosophical. They are often very deep thinkers and can ha [rest of string was truncated]&quot;;.
        /// </summary>
        public static string water_description {
            get {
                return ResourceManager.GetString("water_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Water energies are most likely to suffer health problems related to the kidneys, bladder, reproductive system and adrenal glands, all of which are governed by the element water in Traditional Chinese Medicine.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    It is important for people of this sign to keep warm and take plenty of rest. Alcohol, caffeine, sugar, late nights and stress are particularly depleting for water energies.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    It is also especially important to avoid cold, damp living environments.
        ///&lt;/p&gt;.
        /// </summary>
        public static string water_health {
            get {
                return ResourceManager.GetString("water_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Water energies are sensitive and deep thinkers, and as such, many of them are drawn to poetry, writing, composition, philosophy and some become therapists and healers.
        ///    On the other hand, their natural ability to find a well thought-out and balanced argument means they can make excellent lawyers.
        ///&lt;/p&gt;
        ///.
        /// </summary>
        public static string water_occupations {
            get {
                return ResourceManager.GetString("water_occupations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Water energies&apos; very independen nature coupled with their difficulty to express what they feel deep within them can lead to isolation if they are not careful. 
        ///    It is important for water energies to socialise and communicate. In so doing, others will also benefit from their extraordinary intuition and insight.
        ///&lt;/p&gt;.
        /// </summary>
        public static string water_personal_development {
            get {
                return ResourceManager.GetString("water_personal_development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One yang line encapsulated by two yin lines. Hidden strength and depth within. symbolic of winter&apos;s apparent dormancy on the surface, whilst beneath major change is taking place..
        /// </summary>
        public static string water_trigram {
            get {
                return ResourceManager.GetString("water_trigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;{Title}&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    html
        ///    {
        ///        margin: 0;
        ///		padding: 0;
        ///		font-family: &quot;Segoe UI&quot; , Verdana, Helvetica, Sans-Serif;
        ///		font-size: 100%;
        ///		text-rendering: optimizeLegibility !important;
        ///		-webkit-font-smoothing: antialiased !important;
        ///        margin: 0; 
        ///        color: #333;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Dear {FirstName},&lt;/p&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Thank you for registering with {Comp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeEmail {
            get {
                return ResourceManager.GetString("WelcomeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Like the wind, four wind energies can express anything from stillness to a raging tornado. This energy is one of the most changeable and indeed emotional of the nine energies.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Like thunder energies, also of the element wood, wind energies can be impulsive at times. However, they typically have a gentler, steadier nature than three wood energies.
        ///    Similarly, they are generally a lot more reliable and thoughtful than three energies. They are practical and possess much common sense [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wind_description {
            get {
                return ResourceManager.GetString("wind_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Water energies are most likely to suffer health problems related to the kidneys, bladder, reproductive system and adrenal glands, all of which are governed by the element water in Traditional Chinese Medicine.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    It is important for people of this sign to keep warm and take plenty of rest. Alcohol, caffeine, sugar, late nights and stress are particularly depleting for water energies.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    It is also especially important to avoid cold, damp living environments.
        ///&lt;/p&gt;.
        /// </summary>
        public static string wind_health {
            get {
                return ResourceManager.GetString("wind_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Two upper yang lines denote steadiness and consistency, beneath which lies a gentler, more sensitive yin nature.
        ///&lt;/p&gt;.
        /// </summary>
        public static string wind_trigram {
            get {
                return ResourceManager.GetString("wind_trigram", resourceCulture);
            }
        }
    }
}
